services:
- docker
before_install:
- echo $DOCKER_PASSWD | docker login -u karrot96 --password-stdin
- docker pull karrot96/todo-app
- docker build --tag karrot96/todo-app --cache-from karrot96/todo-app .
- docker push karrot96/todo-app
- docker build --target test --tag my-test-image --cache-from karrot96/todo-app .
script:
- docker run -e MONGO_URL my-test-image
after_success: 
- "./travis/build_and_tag_production.sh"
deploy:
  provider: script
  script: "./travis/deploy_to_heroku.sh"
  on:
    branch: master
env:
  global:
  - secure: ka+vJ+gVf9wWFRXrsGw1dOYGF6xGi63gxjkQ/fLWonr0pDwpVVJEzKDUZ0Xeal07wbK5fnEptxusrKXNUyJpPVXzOHfR7YHbhGkKdaQ3sZ+wKfVSP+HV34hWDM6IGz/YOEewyj+zodJ13UGxENGkk1Bidp+bviYX+kQClSFoSzh+tf1JzalnP12TqlEFdocJZ3ilj4TvMkVaX7Sn65PtLjInaGMxyiyNIp9SSnSejDS1A8I5tIwwodztILvgfmy4K8eJY2UzTr6mnuhV+cKvVTH0jsnVhGRkH02gowBUlKIZ9Zn9B0U+OXcSmWS8VeIMGZ7sL+hOp1fOpQwTVDSIc9cnWsKO3kskinUEJnBez4zn0lY4OfQ7f/iZ3Lf8cyy4emPhxnNCkiuvBqagKFIS5q1saXEQIKuLIBc72iIYnKTHz66CqGoYZy0jRGuF8NR9Wa8Toz6+DtLWdb3sUUj6txZE38tJn05tnSu0LpZLgBmB3XNR1eRKdL0xCJqW1aV2VwpAw98gy4Req4y16NhUwVWSJw2LzsuSLEm8/08375mUmtheY2kj3YBXWFqJT5p4O7Fv7RRy/BAA+aeo4D7k/4zuViApud6Ny5uhBn6iqXaPBgIcIVP7LPAWA0MP9qyg1/NUQ6jNRk9kZ39Xa9ol9jRHMhzuJ1g9CSNw/BZGfuU=
  - secure: wm3fzdS/qmcRc4ylLatJI6Hh3BMTxxo51zbvKyim5b/ao5L9W6BiR80z0vkMyqGf5LFxUJk+2p2Fp+t0ENGFVDevboaYKdzlNGTKXXP7GCuyswVhMYAJ+8zQ3uGI9yN+7iDCUVR2yfu10go0KXqFn2aU2FO2P/zt9VxiCA8R/jvQF/ma3iUr14o1X5RdezbgszYVXzKKY4dWcKgxD88wr8tqJzwp79KGytuMHTtz5vWkw5bvTuAoxpZCXSkwI3FNWFX5ctcz0OZHfYMR5xM9/YMvG7OF9Vqd1ejYhwbuiBofSwskzAifpArQw++RX09bEjxR5l8/8TMvLvePy4EbglqdwpE3+A1qxPo3Vmda8hFYauMDbObx+wyFDtt5qsoXDTUds90IaWbAqhBjcPlNc1vObiQIUQUAa3JAc1DujkEFgboRIwKeBqQPcK0XyPt3ocl4Kq7AinXIY6gZEhTnsumKCTFpQikes0PaFp2wgnDeRYAyHNmAnweHiPqKnc/+vMU+R0XOpilPs87ynoeCcjpmAC50foKxCGI2E8ZqGnT/ScdToVORVOTFZanF3Y+trWt65ppeb6B6FN7SmQat0hcI3kkH4asm65QCZbfko4AmtTIXzh2EJshIbXsi8F1IaMLOLDyZ5rrefBWkR4OD0GuN1wHlAMXUlZfxH7CPIqE=
  - secure: "g8IAxVm6tFQQcv4Nq7QfPWw7R3K/dE+EtoS2uRc3j1NEF+pyeGw5JI6cXKN26KGDhwG0aoTtD2pmlehRXKWPKtOrNMExJW3FtA5mnZgGb8IYrsORPW7XXkDFBZHA+PgtWseCklYNX36aXYysCeV7aEw5h0ypmspX/9gNJEiGBD/hyu493MHlbuz8upA6BYg7/jRlctVTFyQH9w4lrLl74Q/I8aODdI4a/oUYdQLFg/AeIF+CKJ996tkFzQRdkk7JIKytewh2dPoYAzbj1n2EP3H4mRtLrpNWgZSi7I7pVJbT2kAQWyxoNS75ucekLrNtEym/MVaRy9ZU1q36F1oaSHuxEqBIdrL42liNO9L+XYWJ9AJbN3++g+e4d8a8LCSJcGoZgC8dJZiJyHVCf6Ro6iMWNYSP1KAnlum0ucFzKDpZS3vYgbpBClZYK0i2JbeEAd7kzc242XDL8K6HvA7AfuCq7omFVTWou7FBxzqoqDWRMRBVfwCp8CPpIm2nkTthwCB1nz3kfklICevAaEe0DTSacRFBPNu6Gq6KPxcp3EbXnJaA01LwGUveQPWwgn0LbqUqZJv9knMmb/Xke0z/4kNK1i9icFrugBGNl16wEbDDxwum3Lom2QzGguPR2ZNFhH+m5ub9qNMq9qDiI5Yv9u9ML2cTHfMVL/fI4u0aFfI="